# Generated by Django 6.0.5 on 2026-05-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('BEDSITTER', 'Bedsitter'), ('1BR', '1 Bedroom'), ('2BR', '2 Bedroom')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('distance_from_must_km', models.FloatField(help_text='Distance in km from MUST campus')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.JSONField(default=list, help_text="e.g., ['water', 'electricity', 'wifi']")),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
