# Generated by Django 6.0.5 on 2026-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(help_text='Separate with commas (e.g., water, electricity, wifi)'),
        ),
    ]
