# Generated by Django 6.0.5 on 2026-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Separate with commas (e.g., water, electricity, wifi)', null=True),
        ),
    ]
