# Generated by Django 5.0.6 on 2026-09-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_distance_from_must_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SINGLE', 'Single Room'), ('BEDSITTER', 'Bedsitter'), ('SELFCON', 'Self Contained'), ('1BR', '1 Bedroom'), ('2BR', '2 Bedroom'), ('3BR', '3 Bedroom'), ('4BR', '4+ Bedroom'), ('SQ', 'Servant Quarter (SQ)'), ('STANDALONE', 'Standalone House'), ('APARTMENT', 'Apartment/Flat'), ('MAISONETTE', 'Maisonette'), ('SHOP', 'Shop/Commercial Space'), ('OFFICE', 'Office Space'), ('GODOWN', 'Godown/Warehouse'), ('GUESTHOUSE', 'Guest House')], max_length=10),
        ),
    ]
