# Generated by Django 5.0.6 on 2026-09-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
