# Generated by Django 6.0.5 on 2026-05-15 19:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_remove_booking_deposit_paid_alter_booking_property_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MPESA_DIRECT', 'M-Pesa (Direct)'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa code, Bank Ref, etc.', max_length=100, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('tenant_paid_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TENANT_PAID', 'Tenant Marked Paid'), ('COMPLETED', 'Landlord Confirmed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
