# Generated by Django 5.0.6 on 2026-09-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_backfill_tenancies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenancy',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Tenancies'},
        ),
    ]
